### ISSUE TITLE
handle fatal errors that cause pod restarts

### ISSUE THREAD

**Issue by camallen** [zooniverse/sugar#128]
```
$ kubectl logs -p sugar-staging-app-64c4588c7d-m576d 
....
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: read ETIMEDOUT
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)
    at TLSWrap.callbackTrampoline (node:internal/async_hooks:130:17)
Emitted 'error' event on RedisClient instance at:
    at RedisClient.on_error (/node_app/node_modules/redis/index.js:342:14)
    at TLSSocket.<anonymous> (/node_app/node_modules/redis/index.js:223:14)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -110,
  code: 'ETIMEDOUT',
  syscall: 'read'
}
```

The redis client errors are causing the service to fail and the pod to restart. It would be safer to look at modifying the redis client timeouts to accommodate app behaviours and avoid these errors. 

Perhaps #104 may help?

**Comment by eatyourgreens** [comment]
#104 means completely rewriting the Redis code. ☹️

**Comment by camallen** [comment]
> #104 means completely rewriting the Redis code. ☹️

I think that's off the cards for now

**Comment by eatyourgreens** [comment]
I've got a feature branch (#129) that runs locally without crashing, but all the Redis tests are broken at the moment. Pub/sub changed from v3 to v4 so I'm not sure how much I'd trust it until the tests are working again.

**Comment by eatyourgreens** [comment]
None of the promises in the Redis client code have `.catch` blocks, so any Redis client connection errors would, in theory, bubble up and crash the server.

Wrapping Redis connections in try/catch, and handling connection errors, would be one way to deal with this.

**Comment by eatyourgreens** [comment]
Sugar staging is on `node-redis` 4 now.

**Comment by eatyourgreens** [comment]
>>https://github.com/zooniverse/sugar/pull/104 means completely rewriting the Redis code. ☹️
>
>I think that's off the cards for now

Done in #133. PubSub was a bit tricky to convert.

**Comment by eatyourgreens** [comment]
Reverted from Node Redis 4 back to 3, because Sugar kept timing out today.

**Comment by eatyourgreens** [comment]
We're still seeing errors even with Node Redis 3. 😞

**Comment by eatyourgreens** [comment]
Maybe bump the amount of memory available to Node?
https://github.com/zooniverse/science-gossip-data/blob/1d0f5063d9f53a14cf8e963c6c9ecf5837424c9d/package.json#L9

**Comment by eatyourgreens** [comment]
Sugar production is running without errors now, on Node 18.14 with `node-redis` v4.
