### ISSUE TITLE
reflect on JWT data for authentication

### ISSUE THREAD

**Issue by camallen** [zooniverse/sugar#47]
https://github.com/zooniverse/Sugar/blob/75a6912c0bf6cdb27986d55c7fb714651914ede2/lib/panoptes.coffee#L12

Instead of spamming the API use the JWT to determine the user is logged in and their display name.

**Comment by eatyourgreens** [comment]
Does the server need a key to decode tokens?

**Comment by camallen** [comment]
you can find the public keys in https://github.com/zooniverse/panoptes-client.rb/tree/bf0cffdf87b96bc97ed1924a09bb924d7c80d79d/data

**Comment by eatyourgreens** [comment]
Excellent. I might have a go at reading the token in JS. Could be useful in other projects too.

**Comment by camallen** [comment]
the panoptes-client.rb lib has useful details on how to inspect the data in the JWT https://github.com/zooniverse/panoptes-client.rb/blob/bf0cffdf87b96bc97ed1924a09bb924d7c80d79d/lib/panoptes/client/authentication.rb
