### ISSUE TITLE
update the primus.js file for the sugar client

### ISSUE THREAD

**Issue by camallen** [zooniverse/sugar#82]
Discovered via investigations in #81 

The client has a manual version of the primus client library added to the repo - https://github.com/zooniverse/Sugar-Client/tree/11093a1935c9bb70e7cf8021c4aa7673cc4d0ccd

This JS file library needs to be updated whenever the primus server changes to update the client, from https://github.com/primus/primus#client-library
> Do whatever you want with it, but remember to regenerate it every time you change Primus server options. This is important because some properties of the client are set using the server configuration.

Primus was updates a while back in #35 and required a library upgrade in the client as well. However I did not understand how primus provides it's client libraries / how it works with sugar client till last week :( so this never happened. 

Finally it's worth noting that the `primus.js` client file bundles the `engine.io-client` library directly and thus has an old version of the `engine.io-client` https://github.com/primus/primus#transformer-inconsistencies
> Engine.IO and SockJS do not ship their client-side library with their server side component. We're bundling a snapshot of these libraries inside of Primus. We will always be targeting the latest version of these transformers when we bundle the library.

This was the underlying root cause of the issue fixed by #81 the client code (PFE, [sugar dev test harness](https://github.com/zooniverse/sugar/blob/f8f59fc5a9307b2452063daf86e0724ad3db4eb6/public/index.html#L7) etc) uses a very old (<2.0.2) engine.io-client version (derived from the currently installed version of primus), however that `primus.js` in the client might embedd an older version 🤷🏼 . FWIW - the embedded client should be 2.0.2 via the 6.1.0 install of primus - https://github.com/primus/primus/tree/6.1.0/transformers/engine.io

TBC why the PFE code requires the client library to be installed? https://github.com/zooniverse/Panoptes-Front-End/blob/ce7ec636e21dd194c92b3ee9447ad549469639eb/package.json#L15

**Comment by camallen** [comment]
pinging @eatyourgreens @shaunanoordin for attention and welcome to any thoughts

**Comment by eatyourgreens** [comment]
Pinging @mcbouslog who has been working with the Sugar client too.

**Comment by eatyourgreens** [comment]
I'm going to guess that this error triggers in PFE, if you remove the installed client but I'm honestly not sure.
https://github.com/zooniverse/Sugar-Client/blob/11093a1935c9bb70e7cf8021c4aa7673cc4d0ccd/primus.js#L2226-L2234

**Comment by camallen** [comment]
> I could be missing something, but could the client require in `primus` as an external dependency here, rather than loading it from the Sugar client? https://github.com/zooniverse/panoptes-javascript-client/blob/ca40c7b3ab8dbe2d5bd5162510f86f9512b1a6df/lib/sugar.js#L7

Yep - it think so but it'll have to be the same client lib that was generated from the primus server install to keep the two in sync. So we may as well package that up via the [Sugar-Client](https://github.com/zooniverse/Sugar-Client).

> I'm going to guess that this error triggers in PFE, if you remove the installed client but I'm honestly not sure. https://github.com/zooniverse/Sugar-Client/blob/11093a1935c9bb70e7cf8021c4aa7673cc4d0ccd/primus.js#L2226-L2234

I tried this locally by removing the engine.io-client lib directly from PFE https://github.com/zooniverse/Panoptes-Front-End/pull/6097. I see no errors interacting with sugar (notifications) server at all so this leads me to believe my assumptions on the primus lib bundling is how it's working - specifically via `eio` var
- https://github.com/zooniverse/Sugar-Client/blob/11093a1935c9bb70e7cf8021c4aa7673cc4d0ccd/primus.js#L2224
- https://github.com/zooniverse/Sugar-Client/blob/11093a1935c9bb70e7cf8021c4aa7673cc4d0ccd/primus.js#L2434-L2435

**Comment by eatyourgreens** [comment]
That error is thrown in the tests:
https://github.com/zooniverse/Panoptes-Front-End/pull/6097#issuecomment-1041349083

**Comment by camallen** [comment]
> That error is thrown in the tests: [zooniverse/Panoptes-Front-End#6097 (comment)](https://github.com/zooniverse/Panoptes-Front-End/pull/6097#issuecomment-1041349083)

yep - but that code works just fine via `npm start` and at the deployed branch, e.g. visit https://pr-6097.pfe-preview.zooniverse.org/projects/brooke/i-fancy-cats with a logged in user and you should see sugar client working as expected (so primus and engine.io-client libs are present).

**Comment by camallen** [comment]
I think this can close now with the work done to migrate to the latest primus system - feel free to reopen
