### ISSUE TITLE
Presence Timeout

### ISSUE THREAD

**Issue by edpaget** [zooniverse/Sugar#9]
Should we timeout users appearing in Presence if they haven't done anything for a period of time? 

From https://github.com/zooniverse/Panoptes-Front-End/issues/1063

**Comment by parrish** [comment]
They timeout after 30 seconds if they don't send a ping from the socket client

**Comment by edpaget** [comment]
I don't think that was the issue. According the user in the old versions of Talk users who weren't actually doing anything on site would stop appearing in the active list after a period of time even if they had their browser window open. 

In this version it seems if the person is doing nothing on the site, but has the tab open and an active internet connection they'll appear as active indefinitely.

**Comment by parrish** [comment]
Yeah, the old version would mark users active on every request made -- e.g. no requests made would mean not active.

Maybe the heading should be "Users online" instead of "Active users?"

**Comment by chrislintott** [comment]
I like this change. It’s clearer.

Chris
